-- ========================================
-- PHASE VII: Advanced Programming & Auditing
-- Complete working script
-- ========================================

SET SERVEROUTPUT ON;

-- ========================================
-- 1. Drop old objects if they exist
-- ========================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_sensor_bi';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION check_restriction';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE log_audit';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE sensor CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE audit_log CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE holidays CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ========================================
-- 2. Create Holidays Table
-- ========================================
CREATE TABLE holidays (
    holiday_date DATE PRIMARY KEY,
    description VARCHAR2(100)
);

-- Insert sample holidays
INSERT INTO holidays (holiday_date, description) VALUES (TO_DATE('2026-01-01','YYYY-MM-DD'), 'New Year');
INSERT INTO holidays (holiday_date, description) VALUES (TO_DATE('2026-01-20','YYYY-MM-DD'), 'Public Holiday');
COMMIT;

-- ========================================
-- 3. Create Audit Log Table
-- ========================================
CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50),
    action_type VARCHAR2(10),
    table_name VARCHAR2(50),
    action_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(10),
    message VARCHAR2(200)
);

-- ========================================
-- 4. Create log_audit Procedure
-- ========================================
CREATE OR REPLACE PROCEDURE log_audit(
    p_username IN VARCHAR2,
    p_action IN VARCHAR2,
    p_table IN VARCHAR2,
    p_status IN VARCHAR2,
    p_message IN VARCHAR2
)
IS
BEGIN
    INSERT INTO audit_log(username, action_type, table_name, status, message)
    VALUES (p_username, p_action, p_table, p_status, p_message);
END;
/

-- ========================================
-- 5. Create check_restriction Function
-- ========================================
CREATE OR REPLACE FUNCTION check_restriction
RETURN VARCHAR2
IS
    v_day NUMBER;
    v_count NUMBER;
BEGIN
    -- 1=Sunday, 2=Monday, ..., 7=Saturday
    SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'D')) INTO v_day FROM dual;

    -- Deny Mon-Fri
    IF v_day BETWEEN 2 AND 6 THEN
        RETURN 'DENIED: Weekday';
    END IF;

    -- Deny if today is public holiday
    SELECT COUNT(*) INTO v_count
    FROM holidays
    WHERE holiday_date = TRUNC(SYSDATE);

    IF v_count > 0 THEN
        RETURN 'DENIED: Public Holiday';
    END IF;

    RETURN 'ALLOWED';
END;
/

-- ========================================
-- 6. Create Sensor Table
-- ========================================
CREATE TABLE sensor (
    sensor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_type VARCHAR2(50),
    location VARCHAR2(50)
);

-- ========================================
-- 7. Create Trigger trg_sensor_bi
-- ========================================
CREATE OR REPLACE TRIGGER trg_sensor_bi
BEFORE INSERT OR UPDATE OR DELETE ON sensor
FOR EACH ROW
DECLARE
    v_status VARCHAR2(50);
BEGIN
    v_status := check_restriction;

    IF v_status LIKE 'DENIED%' THEN
        log_audit(USER, ORA_SYSEVENT, 'sensor', 'DENIED', v_status);
        RAISE_APPLICATION_ERROR(-20001, 'Action not allowed: ' || v_status);
    ELSE
        log_audit(USER, ORA_SYSEVENT, 'sensor', 'ALLOWED', 'Action executed successfully');
    END IF;
END;
/

-- ========================================
-- 8. Test Queries
-- ========================================

-- a) Check current restriction status
SELECT check_restriction AS restriction_status FROM dual;

-- b) Attempt insert (will show DENIED on weekday)
BEGIN
    INSERT INTO sensor(sensor_type, location)
    VALUES ('Temperature', 'Warehouse');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

-- c) Attempt insert that should succeed for demonstration
-- Temporarily bypass restriction (force ALLOWED)
-- You can uncomment the next lines for testing purposes
/*
CREATE OR REPLACE FUNCTION check_restriction RETURN VARCHAR2 IS
BEGIN
    RETURN 'ALLOWED';
END;
/
INSERT INTO sensor(sensor_type, location) VALUES ('Humidity', 'Lab');
COMMIT;
*/

-- d) Display sensor table (should be empty on weekdays unless forced)
SELECT * FROM sensor;

-- e) Display audit log to see DENIED/ALLOWED attempts
SELECT * FROM audit_log ORDER BY action_date DESC;

