-- Switch to your PDB
ALTER SESSION SET CONTAINER = A_27105_Tracy_EarlySpoilageDetectionSystem_DB;

-- Tables
CREATE TABLE sensor (
    sensor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sensor_type VARCHAR2(50) NOT NULL,
    location VARCHAR2(100),
    installation_date DATE DEFAULT SYSDATE
) TABLESPACE data_ts;

CREATE TABLE product (
    product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50),
    manufacture_date DATE,
    expiry_date DATE
) TABLESPACE data_ts;

CREATE TABLE measurement (
    measurement_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sensor_id NUMBER NOT NULL,
    measure_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    temperature NUMBER(5,2) CHECK (temperature >= -50 AND temperature <= 100),
    humidity NUMBER(5,2) CHECK (humidity >= 0 AND humidity <= 100),
    spoilage_index NUMBER(5,2) DEFAULT 0,
    CONSTRAINT fk_sensor FOREIGN KEY (sensor_id) REFERENCES sensor(sensor_id)
) TABLESPACE data_ts;

-- Indexes
CREATE INDEX idx_measurement_sensor ON measurement(sensor_id) TABLESPACE index_ts;
CREATE INDEX idx_product_category ON product(category) TABLESPACE index_ts;

-- Sample data
INSERT INTO sensor (sensor_type, location) VALUES ('Temperature', 'Warehouse 1');
INSERT INTO product (product_name, category, manufacture_date, expiry_date)
VALUES ('Tomatoes', 'Vegetable', DATE '2025-11-01', DATE '2025-11-10');
INSERT INTO measurement (sensor_id, temperature, humidity, spoilage_index) VALUES (1, 25.5, 60, 0.2);

COMMIT;
